spring.application.name=journalApp
spring.mongodb.uri=mongodb+srv://arjundeykumar_db_user:id3LvVkOz2uus2t6@cluster0.hanqc8c.mongodb.net/?appName=Cluster0
spring.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true